#!/bin/bash

cd -- "$( dirname -- "${BASH_SOURCE[0]}" )"

DATE=`date +%Y/%m/%d/`

mkdir -p roughtime/$DATE/$1

roughstamp/target/debug/roughstamp stamp $1 roughtime.cloudflare.com:2002 roughtime/$DATE/$1/roughtime.cloudflare.com "gD63hSj3ScS+wuOeGrubXlq35N1c5Lby/S+T7MNTjxo=" &
roughstamp/target/debug/roughstamp stamp $1 roughtime.int08h.com:2002 roughtime/$DATE/$1/roughtime.int08h.com "AW5uAoTSTDfG5NfY1bTh08GUnOqlRb+HVhbJ3ODJvsE=" &
roughstamp/target/debug/roughstamp stamp $1 time.0xt.ca:2002 roughtime/$DATE/$1/time.0xt.ca "iBVjxg/1j7y1+kQUTBYdTabxCppesU/07D4PMDJk2WA=" &
